- **Tensors are a specialized data structure that are very similar to arrays and matices**
- **In PyTorch, we use tensors to encode the inputs and outputs of a model, as well the model's parameters**
- **Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators**
- **Tensors are also optimized for automatic differentiation**


In [1]:
import torch
import numpy as np

### Initializing a Tensor

**Directly from data** <br >
Tensors can be created directly from data. The data type is automatically inferred.

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array** <br>
Tensors can be created from NumPy arrays and vice versa 

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**From another tensor:** <br>
The new tensor retains the properties (shape, datatype) of the arguments tensor, unless explicitly overridden.

In [8]:
x_ones = torch.ones_like(x_data) #retains the properties of the x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_ones_modified =torch.ones_like(x_data, dtype=torch.float) #overrides the datatype of x_data
print(f"Ones tensor  (data type modified): \n {x_ones_modified} \n") 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones tensor  (data type modified): 
 tensor([[1., 1.],
        [1., 1.]]) 



**With random or constant values** <br>
`shape` is a tuple of tensor dimesions. In the functions below, it determines the dimentionality of the output tensor.

In [10]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensors: \n {rand_tensor} \n")
print(f"Ones Tensors: \n {ones_tensor} \n")
print(f"Zeros Tensors: \n {zeros_tensor } \n")

Random Tensors: 
 tensor([[2.2137e-04, 3.5374e-01, 6.4552e-01],
        [1.9461e-02, 7.5213e-01, 7.2621e-01]]) 

Ones Tensors: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensors: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Attributes of a Tensor

**Tensor attributes describe their shape, datatype, and the device on which they are stored**

In [ ]:
tensor = torch.ones(4,5)

print(f"Shape of the tensor: \n {tensor.shape