## Tensors

- **Tensors are a specialized data structure that are very similar to arrays and matices**
- **In PyTorch, we use tensors to encode the inputs and outputs of a model, as well the model's parameters**
- **Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators**
- **Tensors are also optimized for automatic differentiation**


In [2]:
import torch
import numpy as np

### Initializing a Tensor

**Directly from data** <br >
Tensors can be created directly from data. The data type is automatically inferred.

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array** <br>
Tensors can be created from NumPy arrays and vice versa 

In [4]:

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**From another tensor:** <br>
The new tensor retains the properties (shape, datatype) of the arguments tensor, unless explicitly overridden.

In [5]:
x_ones = torch.ones_like(x_data) #retains the properties of the x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_ones_modified =torch.ones_like(x_data, dtype=torch.float) #overrides the datatype of x_data
print(f"Ones tensor  (data type modified): \n {x_ones_modified} \n") 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones tensor  (data type modified): 
 tensor([[1., 1.],
        [1., 1.]]) 



**With random or constant values** <br>
`shape` is a tuple of tensor dimesions. In the functions below, it determines the dimentionality of the output tensor.

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensors: \n {rand_tensor} \n")
print(f"Ones Tensors: \n {ones_tensor} \n")
print(f"Zeros Tensors: \n {zeros_tensor } \n")

Random Tensors: 
 tensor([[5.3254e-01, 8.5862e-01, 4.1683e-01],
        [9.0053e-01, 8.5098e-04, 3.2986e-01]]) 

Ones Tensors: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensors: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Attributes of a Tensor

**Tensor attributes describe their shape, datatype, and the device on which they are stored**

In [11]:
tensor = torch.ones(4,5)

print(f"Shape of the tensor:  {tensor.shape} \n")
print(f"Datatype of the tensor:  {tensor.dtype} \n")
print(f"Device of the tensor:  {tensor.device} \n")

Shape of the tensor:  torch.Size([4, 5]) 

Datatype of the tensor:  torch.float32 

Device of the tensor:  cpu 



### Operations on Tensors

**By default, tensors are created on the CPU. We need to explicilty move tensors to the GPU using `.to` method (after checking for GPU avalability). <br>
Keep in mind that copying large tensors across devices can be expensive in term of time and memory**

In [13]:
#We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(f"Device of the tensor: {tensor.device} \n") 

Device of the tensor: cuda:0 



**Standard numpy-like indexing and slicing**

In [16]:
tensor = torch.ones(4,4)
tensor[:, -1] = 0
tensor

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

**Joining tensors:** You can use `torch.cat` to concatenate a squence of tensors along a given dimensions.

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])

In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
t1

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

**Arithmetic Operations**

In [25]:
# This computes the matrix multiplication between two tensors. 

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This compute the element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

**Single-element tensors** If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`

In [26]:
agg = tensor.sum()
agg_item = agg.item()
agg_item

12.0

**In-place Operations** Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example `x.copy_(y)`, `x.t_()`, will change `x`.

In [45]:
x = torch.ones_like(tensor)
tensor = x.t_()
print(f"x: \n {x} \ntensor: \n {tensor} \n")

tensor.add_(5) 

print(f"x: \n {x} \ntensor: \n {tensor} \n")

x: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 
tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

x: 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 
tensor: 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 



In [47]:
x = torch.ones_like(tensor)
x.copy_(tensor)
print(f"x: \n {x} \ntensor: \n {tensor} \n")

tensor.add_(5) 

print(f"x: \n {x} \ntensor: \n {tensor} \n")

x: 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 
tensor: 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 

x: 
 tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 
tensor: 
 tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]]) 



### Bridge with NumPy

- **Tensors on the CPU and NumPy arrays  can share their underlying memory, locations, and changing one will change the other**

Tensor to NumPy array

In [48]:
t = torch.ones(5)
print(f't: {t}')
n= t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [50]:
t.add_(2)
print(f't: {t}')
print(f"n: {n}")


t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [51]:
#and vice versa
np.add(n, 5, out=n)
print(f't: {t}')
print(f"n: {n}")

t: tensor([8., 8., 8., 8., 8.])
n: [8. 8. 8. 8. 8.]
